import File from "../models/File.js";
import { nanoid } from "nanoid";
import { DeleteObjectCommand } from "@aws-sdk/client-s3";
import { s3 } from "../config/s3.js"; // Ensure this path points to your S3 client config

// @desc    Upload file to S3 and save metadata to MongoDB
export const uploadFile = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ message: "No file provided" });
    }

    const newFile = await File.create({
      fileName: req.file.originalname,
      fileUrl: req.file.location, // The S3 URL generated by multer-s3
      fileSize: req.file.size,
      code: nanoid(6), // Unique 6-character sharing code
      user: req.user ? req.user.id : null, 
    });

    res.json({ 
      link: `${process.env.FRONTEND_URL}/file/${newFile.code}`,
      file: newFile 
    });
  } catch (err) {
    console.error("Upload Controller Error:", err);
    res.status(500).json({ message: "Upload failed", error: err.message });
  }
};

// @desc    Get file details by 6-digit code
export const getFile = async (req, res) => {
  try {
    const file = await File.findOne({ code: req.params.code });
    if (!file) return res.status(404).json({ message: "File not found" });
    
    res.json({ 
        fileName: file.fileName, 
        downloadUrl: file.fileUrl,
        fileSize: file.fileSize 
    });
  } catch (err) {
    res.status(500).json({ message: "Server error" });
  }
};

// @desc    Get all files uploaded by the logged-in user
export const getUserFiles = async (req, res) => {
  try {
    const files = await File.find({ user: req.user.id }).sort({ createdAt: -1 });
    res.json(files);
  } catch (err) {
    res.status(500).json({ message: "Error fetching your history" });
  }
};

// @desc    Delete file from both S3 and MongoDB
export const deleteFile = async (req, res) => {
  try {
    // 1. Find the file in DB to get the S3 Key
    const file = await File.findOne({ _id: req.params.id, user: req.user.id });
    
    if (!file) {
      return res.status(404).json({ message: "File not found or unauthorized" });
    }

    // 2. Extract S3 Key from the URL
    // URL format: https://bucket-name.s3.region.amazonaws.com/unique-filename.ext
    const s3Key = file.fileUrl.split('/').pop();

    // 3. Delete from AWS S3 storage
    const deleteParams = {
      Bucket: process.env.AWS_BUCKET_NAME,
      Key: s3Key,
    };

    try {
      await s3.send(new DeleteObjectCommand(deleteParams));
      console.log(`Successfully deleted ${s3Key} from S3 bucket`);
    } catch (s3Err) {
      // Log S3 error but continue DB deletion so the UI stays in sync
      console.error("AWS S3 Deletion Error:", s3Err);
    }

    // 4. Delete the record from MongoDB
    await file.deleteOne();

    res.json({ message: "File deleted successfully from cloud and history" });
  } catch (err) {
    console.error("Delete Controller Error:", err);
    res.status(500).json({ message: "Failed to delete file" });
  }
};