import { useState } from "react";
import { useDropzone } from "react-dropzone";
import api from "../services/api";
import toast from "react-hot-toast";
import ProgressBar from "./ProgressBar";
import FileInfo from "./FileInfo";
import FileCard from "./FileCard";

function UploadBox() {
  const [file, setFile] = useState(null);
  const [progress, setProgress] = useState(0);
  const [link, setLink] = useState("");
  const [loading, setLoading] = useState(false);

  const onDrop = (files) => {
    setFile(files[0]);
    setProgress(0);
  };

  const { getRootProps, getInputProps } = useDropzone({ onDrop, multiple: false });

  const uploadFile = async () => {
    if (!file) return toast.error("Please select a file");
    setLoading(true);

    const formData = new FormData();
    formData.append("file", file); // Key must match backend upload.single('file')

    try {
      const res = await api.post("/files/upload", formData, {
        headers: { "Content-Type": "multipart/form-data" },
        onUploadProgress: (p) => setProgress(Math.round((p.loaded * 100) / p.total)),
      });
      setLink(res.data.link); // Link generated by backend (e.g., /file/abc123)
      toast.success("Uploaded to Cloud!");
    } catch (err) {
      toast.error(err.response?.data?.message || "Upload failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="w-full max-w-xl mx-auto px-4">
      {!link ? (
        <div className="bg-white border rounded-2xl p-4 sm:p-8 shadow-sm">
          <div {...getRootProps()} className="border-2 border-dashed border-gray-200 rounded-xl p-8 sm:p-12 text-center cursor-pointer hover:border-[#FF5B5B] transition-colors">
            <input {...getInputProps()} />
            <p className="text-gray-500">Drag & drop or <span className="text-[#FF5B5B]">browse</span></p>
          </div>
          <FileInfo file={file} />
          {progress > 0 && <ProgressBar progress={progress} />}
          <button 
            disabled={loading || !file}
            onClick={uploadFile} 
            className="bg-[#FF5B5B] text-white w-full py-3 rounded-xl mt-6 font-semibold disabled:bg-gray-300 transition-all hover:shadow-lg"
          >
            {loading ? "Uploading..." : "Upload"}
          </button>
        </div>
      ) : (
        <FileCard link={link} />
      )}
    </div>
  );
}
export default UploadBox; 